name: Deploy to Production

on:
  push:
    branches:
      - Production

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push discord bot image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lcskopje_private:eestecer

      - name: Login to Base Server and Restart Services
        env:
          GH_SECRET_KEY: ${{ secrets.GH_SECRET_KEY }}
        run: |
          echo "${{secrets.GH_SECRET_KEY}}" > temp_secret
          chmod 600 temp_secret  # Restrict file permissions
          ssh -T -o StrictHostKeyChecking=no -p 1122 -i temp_secret -tt eestec@ip.42.mk << 'EOF'
            touch pedzo
            cd eestecmk
            cd eestecer
            docker-compose pull
            docker-compose up -d
            exit
          EOF